services:
  whisperx-api-server-cpu:
    image: whisperx-api-server-cpu
    build:
      context: .
      dockerfile: Dockerfile.cpu
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/healthcheck || exit 1"]
    command: uvicorn --factory whisperx_api_server.main:create_app
    ports:
      - 8085:8000
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
      - torch_cache:/root/.cache/torch
volumes:
  hugging_face_cache:
  torch_cache:
